# Generated by Django 6.0.4 on 2026-04-18 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(blank=True, max_length=256)),
                ('rating', models.CharField(blank=True, max_length=64)),
                ('reviews_count', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('book_url', models.URLField(blank=True, max_length=1024)),
                ('summary', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=128)),
                ('sentiment', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=256, unique=True)),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='books.book')),
            ],
        ),
    ]
